## Import libraries

In [2]:
import pandas as pd
import numpy as np

# Import

In [3]:
refinitiv_controls = pd.read_excel('data/Refinitiv_ Controls.xlsx', sheet_name="All controls_Agri", header=None,skiprows=3, names=[
    "Identifier (RIC)", 
    "Company Name", 
    "Ticker Symbol",
    "Date Became Public", 
    "NAICS Industry Group Name", 
    "Business Description", 
    "SD 2005", "SD 2006", "SD 2007", "SD 2008", "SD 2009", "SD 2010", "SD 2011", "SD 2012", "SD 2013", "SD 2014", "SD 2015", "SD 2016", "SD 2017", "SD 2018", "SD 2019", "SD 2020", "SD 2021", "SD 2022",
    "T 2022", "T 2021", "T 2020", "T 2019", "T 2018", "T 2017", "T 2016", "T 2015", "T 2014", "T 2013", "T 2012", "T 2011", "T 2010", "T 2009", "T 2008", "T 2007", "T 2006", "T 2005",
    "T% 2022", "T% 2021", "T% 2020", "T% 2019", "T% 2018", "T% 2017", "T% 2016", "T% 2015", "T% 2014", "T% 2013", "T% 2012", "T% 2011", "T% 2010", "T% 2009", "T% 2008", "T% 2007", "T% 2006", "T% 2005",
    "CMC 2022", "CMC 2021", "CMC 2020", "CMC 2019", "CMC 2018", "CMC 2017", "CMC 2016", "CMC 2015", "CMC 2014", "CMC 2013", "CMC 2012", "CMC 2011", "CMC 2010", "CMC 2009", "CMC 2008", "CMC 2007", "CMC 2006", "CMC 2005",
    "BVS 2021", "BVS 2020", "BVS 2019", "BVS 2018", "BVS 2017", "BVS 2016", "BVS 2015", "BVS 2014", "BVS 2013", "BVS 2012", "BVS 2011", "BVS 2010", "BVS 2009", "BVS 2008", "BVS 2007", "BVS 2006", "BVS 2005",
    "TA 2021", "TA 2020", "TA 2019", "TA 2018", "TA 2017", "TA 2016", "TA 2015", "TA 2014", "TA 2013", "TA 2012", "TA 2011", "TA 2010", "TA 2009", "TA 2008", "TA 2007", "TA 2006", "TA 2005",
    "NIT 2021", "NIT 2020", "NIT 2019", "NIT 2018", "NIT 2017", "NIT 2016", "NIT 2015", "NIT 2014", "NIT 2013", "NIT 2012", "NIT 2011", "NIT 2010", "NIT 2009", "NIT 2008", "NIT 2007", "NIT 2006", "NIT 2005",
    "TDTEV 2022", "TDTEV 2021", "TDTEV 2020", "TDTEV 2019", "TDTEV 2018", "TDTEV 2017", "TDTEV 2016", "TDTEV 2015", "TDTEV 2014", "TDTEV 2013", "TDTEV 2012", "TDTEV 2011", "TDTEV 2010", "TDTEV 2009", "TDTEV 2008", "TDTEV 2007", "TDTEV 2006", "TDTEV 2005",
    "CET 2021", "CET 2020", "CET 2019", "CET 2018", "CET 2017", "CET 2016", "CET 2015", "CET 2014", "CET 2013", "CET 2012", "CET 2011", "CET 2010", "CET 2009", "CET 2008", "CET 2007", "CET 2006", "CET 2005",
    "PPENT 2021", "PPENT 2020", "PPENT 2019", "PPENT 2018", "PPENT 2017", "PPENT 2016", "PPENT 2015", "PPENT 2014", "PPENT 2013", "PPENT 2012", "PPENT 2011", "PPENT 2010", "PPENT 2009", "PPENT 2008", "PPENT 2007", "PPENT 2006", "PPENT 2005",
    "BNEPS% 2021", "BNEPS% 2020", "BNEPS% 2019", "BNEPS% 2018", "BNEPS% 2017", "BNEPS% 2016", "BNEPS% 2015", "BNEPS% 2014", "BNEPS% 2013", "BNEPS% 2012", "BNEPS% 2011", "BNEPS% 2010", "BNEPS% 2009", "BNEPS% 2008", "BNEPS% 2007", "BNEPS% 2006", "BNEPS% 2005"
], index_col=None)

In [4]:
# Remove SD datas
refinitiv_controls = refinitiv_controls.drop(columns=['SD 2005', 'SD 2006', 'SD 2007', 'SD 2008', 'SD 2009', 'SD 2010', 'SD 2011', 'SD 2012', 'SD 2013', 'SD 2014', 'SD 2015', 'SD 2016', 'SD 2017', 'SD 2018', 'SD 2019', 'SD 2020', 'SD 2021', 'SD 2022'])

# Remove 2022 datas
refinitiv_controls = refinitiv_controls.drop(columns=['T 2022', 'T% 2022', 'CMC 2022', 'TDTEV 2022'])

In [5]:
test = pd.DataFrame(refinitiv_controls, columns=["Ticker Symbol","BVS 2021", "BVS 2020", "BVS 2019", "BVS 2018", "BVS 2017", "BVS 2016", "BVS 2015", "BVS 2014", "BVS 2013", "BVS 2012", "BVS 2011", "BVS 2010", "BVS 2009", "BVS 2008", "BVS 2007", "BVS 2006", "BVS 2005"], index=[0,1])

test_melt = pd.melt(test, id_vars=["Ticker Symbol"], var_name="Year", value_name="BVS")
test_sort = test_melt.sort_values(by=['Ticker Symbol', 'Year'])
test_sort

   Ticker Symbol      Year        BVS
33          CLEX  BVS 2005   0.214784
31          CLEX  BVS 2006   0.143686
29          CLEX  BVS 2007   0.160628
27          CLEX  BVS 2008   0.154247
25          CLEX  BVS 2009   0.166000
23          CLEX  BVS 2010   0.161573
21          CLEX  BVS 2011   0.159053
19          CLEX  BVS 2012  -4.866240
17          CLEX  BVS 2013  -5.772788
15          CLEX  BVS 2014  -5.257303
13          CLEX  BVS 2015  -4.861149
11          CLEX  BVS 2016  -4.805083
9           CLEX  BVS 2017  -5.658696
7           CLEX  BVS 2018  -5.487834
5           CLEX  BVS 2019  -5.388767
3           CLEX  BVS 2020  -5.949813
1           CLEX  BVS 2021  -5.756002
32           SIP  BVS 2005  15.150206
30           SIP  BVS 2006  17.415294
28           SIP  BVS 2007  22.277233
26           SIP  BVS 2008  27.608040
24           SIP  BVS 2009  33.168747
22           SIP  BVS 2010  41.170655
20           SIP  BVS 2011  47.824779
18           SIP  BVS 2012  53.153239
16           SIP  BVS 2013  57.151053
14           SIP  BVS 2014  46.226999
12           SIP  BVS 2015  46.931903
10           SIP  BVS 2016  50.675885
8            SIP  BVS 2017  60.699770
6            SIP  BVS 2018  61.758075
4            SIP  BVS 2019  60.338344
2            SIP  BVS 2020  61.298387
0            SIP  BVS 2021  69.926552

In [6]:
df = pd.DataFrame({'City': ['Houston', 'Austin', 'Hoover'],
                   'State': ['Texas', 'Texas', 'Alabama'],
                   'Name':['Aria', 'Penelope', 'Niko'],
                   'Mango':[4, 10, 90],
                   'Orange': [10, 8, 14], 
                   'Watermelon':[40, 99, 43],
                   'Gin':[16, 200, 34],
                   'Vodka':[20, 33, 18]},
                 columns=['City', 'State', 'Name', 'Mango', 'Orange', 'Watermelon', 'Gin', 'Vodka'])

df1 = df.melt(id_vars=['City', 'State'], 
              value_vars=['Mango', 'Orange', 'Watermelon'],
              var_name='Fruit', value_name='Pounds')
df2 = df.melt(id_vars=['City', 'State'], 
              value_vars=['Gin', 'Vodka'], 
              var_name='Drink', value_name='Ounces')

df11 = df1.set_index(['City', 'State', df1.groupby(['City', 'State']).cumcount()])
df22 = df2.set_index(['City', 'State', df2.groupby(['City', 'State']).cumcount()])


df3 = (pd.concat([df11, df22],axis=1)
         .sort_index(level=2)
         .reset_index(level=2, drop=True)
         .reset_index())

In [7]:
df

      City    State      Name  Mango  Orange  Watermelon  Gin  Vodka
0  Houston    Texas      Aria      4      10          40   16     20
1   Austin    Texas  Penelope     10       8          99  200     33
2   Hoover  Alabama      Niko     90      14          43   34     18

In [8]:
df1

      City    State       Fruit  Pounds
0  Houston    Texas       Mango       4
1   Austin    Texas       Mango      10
2   Hoover  Alabama       Mango      90
3  Houston    Texas      Orange      10
4   Austin    Texas      Orange       8
5   Hoover  Alabama      Orange      14
6  Houston    Texas  Watermelon      40
7   Austin    Texas  Watermelon      99
8   Hoover  Alabama  Watermelon      43

In [10]:
df11

                        Fruit  Pounds
City    State
Houston Texas   0       Mango       4
Austin  Texas   0       Mango      10
Hoover  Alabama 0       Mango      90
Houston Texas   1      Orange      10
Austin  Texas   1      Orange       8
Hoover  Alabama 1      Orange      14
Houston Texas   2  Watermelon      40
Austin  Texas   2  Watermelon      99
Hoover  Alabama 2  Watermelon      43

In [11]:
df3

      City    State       Fruit  Pounds  Drink  Ounces
0   Austin    Texas       Mango      10    Gin   200.0
1   Hoover  Alabama       Mango      90    Gin    34.0
2  Houston    Texas       Mango       4    Gin    16.0
3   Austin    Texas      Orange       8  Vodka    33.0
4   Hoover  Alabama      Orange      14  Vodka    18.0
5  Houston    Texas      Orange      10  Vodka    20.0
6   Austin    Texas  Watermelon      99    NaN     NaN
7   Hoover  Alabama  Watermelon      43    NaN     NaN
8  Houston    Texas  Watermelon      40    NaN     NaN